<a href="https://colab.research.google.com/github/UtkarshSharma-004/X-ray-lungs-disease-Detection/blob/main/Copy_of_CapstoneProject(CNN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub
path = kagglehub.dataset_download("nih-chest-xrays/data")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/nih-chest-xrays/data?dataset_version_number=3...

100%|██████████| 42.0G/42.0G [08:07<00:00, 92.6MB/s]

Extracting files...

In [ ]:
path

In [ ]:
import shutil

print("Downloaded to:", path)

# Destination folder in Colab
destination = "/content/drive/MyDrive/Capstone Project/nih_chest_xrays"

# Move dataset to /content
shutil.copytree(path, destination, dirs_exist_ok=True)

print("Dataset copied to:", destination)

Downloaded to: /root/.cache/kagglehub/datasets/nih-chest-xrays/data/versions/3

In [ ]:
destination = "/content/drive/MyDrive/Capstone Project/nih_chest_xrays"

In [ ]:
# # Delete the original downloaded folder
# shutil.rmtree(path)

# print("Original dataset deleted from:", path)

Original dataset deleted from: /root/.cache/kagglehub/datasets/nih-chest-xrays/data/versions/3

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df= pd.read_csv(f'{destination}/Data_Entry_2017.csv')

In [ ]:
df.sample(10)

,Image Index,Finding Labels,Follow-up #,Patient ID,Patient Age,Patient Gender,View Position,OriginalImage[Width,Height],OriginalImagePixelSpacing[x,y],Unnamed: 11
86279,00021277_003.png,Nodule|Pleural_Thickening,3,21277,19,M,AP,2956,2544,0.139,0.139,NaN
32979,00008636_000.png,Mass,0,8636,58,F,AP,2500,2048,0.171,0.171,NaN
51082,00012907_010.png,No Finding,10,12907,40,M,PA,2992,2991,0.143,0.143,NaN
9961,00002582_010.png,Atelectasis|Effusion,10,2582,62,M,AP,2500,2048,0.168,0.168,NaN
104578,00027982_005.png,No Finding,5,27982,36,M,AP,3056,2544,0.139,0.139,NaN
64648,00015956_021.png,Infiltration,21,15956,67,M,AP,2500,2048,0.168,0.168,NaN
102801,00027415_034.png,Infiltration,34,27415,23,M,AP,3056,2544,0.139,0.139,NaN
99486,00026332_000.png,Atelectasis|Effusion,0,26332,55,M,PA,3056,2544,0.139,0.139,NaN
88110,00021796_007.png,Effusion,7,21796,54,M,AP,3056,2544,0.139,0.139,NaN
56607,00014083_000.png,No Finding,0,14083,22,F,PA,2990,2991,0.143,0.143,NaN

In [ ]:
df['Finding Labels'].value_counts()

Finding Labels
No Finding                                                           60361
Infiltration                                                          9547
Atelectasis                                                           4215
Effusion                                                              3955
Nodule                                                                2705
                                                                     ...
Hernia|Infiltration|Nodule                                               1
Cardiomegaly|Hernia|Mass                                                 1
Atelectasis|Effusion|Infiltration|Pneumonia|Pneumothorax                 1
Atelectasis|Cardiomegaly|Consolidation|Effusion|Infiltration|Mass        1
Emphysema|Mass|Nodule|Pleural_Thickening                                 1
Name: count, Length: 836, dtype: int64

In [ ]:
df[df['Finding Labels']=='No Finding']

,Image Index,Finding Labels,Follow-up #,Patient ID,Patient Age,Patient Gender,View Position,OriginalImage[Width,Height],OriginalImagePixelSpacing[x,y],Unnamed: 11
3,00000002_000.png,No Finding,0,2,81,M,PA,2500,2048,0.171,0.171,NaN
13,00000005_000.png,No Finding,0,5,69,F,PA,2048,2500,0.168,0.168,NaN
14,00000005_001.png,No Finding,1,5,69,F,AP,2500,2048,0.168,0.168,NaN
15,00000005_002.png,No Finding,2,5,69,F,AP,2500,2048,0.168,0.168,NaN
16,00000005_003.png,No Finding,3,5,69,F,PA,2992,2991,0.143,0.143,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
112114,00030801_000.png,No Finding,0,30801,39,M,PA,2500,2048,0.168,0.168,NaN
112116,00030802_000.png,No Finding,0,30802,29,M,PA,2048,2500,0.168,0.168,NaN
112117,00030803_000.png,No Finding,0,30803,42,F,PA,2048,2500,0.168,0.168,NaN
112118,00030804_000.png,No Finding,0,30804,30,F,PA,2048,2500,0.168,0.168,NaN
112119,00030805_000.png,No Finding,0,30805,27,M,PA,2048,2500,0.171,0.171,NaN

In [ ]:
import os

imageFolderPaths = []


for folderName in os.listdir(destination):
  # print(folderName)
  if folderName.startswith("images_"):
    folderPath = os.path.join(destination, folderName, "images")
    if os.path.isdir(folderPath):
        imageFolderPaths.append(folderPath)

imageFolderPaths = sorted(imageFolderPaths)
print(imageFolderPaths)

['/content/drive/MyDrive/Capstone Project/nih_chest_xrays/images_001/images', '/content/drive/MyDrive/Capstone Project/nih_chest_xrays/images_002/images', '/content/drive/MyDrive/Capstone Project/nih_chest_xrays/images_003/images', '/content/drive/MyDrive/Capstone Project/nih_chest_xrays/images_005/images', '/content/drive/MyDrive/Capstone Project/nih_chest_xrays/images_006/images', '/content/drive/MyDrive/Capstone Project/nih_chest_xrays/images_007/images', '/content/drive/MyDrive/Capstone Project/nih_chest_xrays/images_008/images', '/content/drive/MyDrive/Capstone Project/nih_chest_xrays/images_009/images', '/content/drive/MyDrive/Capstone Project/nih_chest_xrays/images_010/images', '/content/drive/MyDrive/Capstone Project/nih_chest_xrays/images_011/images', '/content/drive/MyDrive/Capstone Project/nih_chest_xrays/images_012/images']

In [ ]:
len(imageFolderPaths)

12

In [ ]:
imageRows = []

for folderPath in imageFolderPaths:
    for imageName in os.listdir(folderPath):
        imageRows.append({
            "imageIndex": imageName,
            "imagePath": os.path.join(folderPath, imageName)
        })

imagePathDf = pd.DataFrame(imageRows)

print(imagePathDf.shape)
imagePathDf.head()

(101038, 2)

         imageIndex                                          imagePath
0  00000782_002.png  /content/drive/MyDrive/Capstone Project/nih_ch...
1  00001314_000.png  /content/drive/MyDrive/Capstone Project/nih_ch...
2  00000761_004.png  /content/drive/MyDrive/Capstone Project/nih_ch...
3  00000798_024.png  /content/drive/MyDrive/Capstone Project/nih_ch...
4  00000859_000.png  /content/drive/MyDrive/Capstone Project/nih_ch...

In [ ]:
df.rename(columns={'Image Index':'imageIndex'},inplace=True)

In [ ]:
df.columns

Index(['imageIndex', 'Finding Labels', 'Follow-up #', 'Patient ID',
       'Patient Age', 'Patient Gender', 'View Position', 'OriginalImage[Width',
       'Height]', 'OriginalImagePixelSpacing[x', 'y]', 'Unnamed: 11'],
      dtype='object')

In [ ]:
masterDf = df.merge(imagePathDf, on="imageIndex", how="left")
masterDf = masterDf.dropna(subset=["imagePath"]).reset_index(drop=True)

print(masterDf.shape)
print("Missing imagePath:", masterDf["imagePath"].isna().sum())
masterDf.head()

(101038, 13)
Missing imagePath: 0

,imageIndex,Finding Labels,Follow-up #,Patient ID,Patient Age,Patient Gender,View Position,OriginalImage[Width,Height],OriginalImagePixelSpacing[x,y],Unnamed: 11,imagePath
0,00000001_000.png,Cardiomegaly,0,1,58,M,PA,2682,2749,0.143,0.143,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...
1,00000001_001.png,Cardiomegaly|Emphysema,1,1,58,M,PA,2894,2729,0.143,0.143,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...
2,00000001_002.png,Cardiomegaly|Effusion,2,1,58,M,PA,2500,2048,0.168,0.168,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...
3,00000002_000.png,No Finding,0,2,81,M,PA,2500,2048,0.171,0.171,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...
4,00000003_000.png,Hernia,0,3,81,F,PA,2582,2991,0.143,0.143,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...

In [ ]:
masterDf[masterDf['Finding Labels'].isin(['No Finding','Infiltration'])].columns

Index(['imageIndex', 'Finding Labels', 'Follow-up #', 'Patient ID',
       'Patient Age', 'Patient Gender', 'View Position', 'OriginalImage[Width',
       'Height]', 'OriginalImagePixelSpacing[x', 'y]', 'Unnamed: 11',
       'imagePath'],
      dtype='object')

In [ ]:
filteredDf = masterDf[masterDf['Finding Labels'].isin(['No Finding','Infiltration'])].copy()

print(filteredDf.shape)
filteredDf.head()

(62888, 13)

,imageIndex,Finding Labels,Follow-up #,Patient ID,Patient Age,Patient Gender,View Position,OriginalImage[Width,Height],OriginalImagePixelSpacing[x,y],Unnamed: 11,imagePath
3,00000002_000.png,No Finding,0,2,81,M,PA,2500,2048,0.171,0.171,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...
13,00000005_000.png,No Finding,0,5,69,F,PA,2048,2500,0.168,0.168,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...
14,00000005_001.png,No Finding,1,5,69,F,AP,2500,2048,0.168,0.168,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...
15,00000005_002.png,No Finding,2,5,69,F,AP,2500,2048,0.168,0.168,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...
16,00000005_003.png,No Finding,3,5,69,F,PA,2992,2991,0.143,0.143,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...

In [ ]:
filteredDf['label'] = filteredDf['Finding Labels'].map({
    'No Finding':0,
    'Infiltration':1
})

In [ ]:
filteredDf

,imageIndex,Finding Labels,Follow-up #,Patient ID,Patient Age,Patient Gender,View Position,OriginalImage[Width,Height],OriginalImagePixelSpacing[x,y],Unnamed: 11,imagePath,label
3,00000002_000.png,No Finding,0,2,81,M,PA,2500,2048,0.171,0.171,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...,0
13,00000005_000.png,No Finding,0,5,69,F,PA,2048,2500,0.168,0.168,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...,0
14,00000005_001.png,No Finding,1,5,69,F,AP,2500,2048,0.168,0.168,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...,0
15,00000005_002.png,No Finding,2,5,69,F,AP,2500,2048,0.168,0.168,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...,0
16,00000005_003.png,No Finding,3,5,69,F,PA,2992,2991,0.143,0.143,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101032,00030801_000.png,No Finding,0,30801,39,M,PA,2500,2048,0.168,0.168,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...,0
101034,00030802_000.png,No Finding,0,30802,29,M,PA,2048,2500,0.168,0.168,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...,0
101035,00030803_000.png,No Finding,0,30803,42,F,PA,2048,2500,0.168,0.168,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...,0
101036,00030804_000.png,No Finding,0,30804,30,F,PA,2048,2500,0.168,0.168,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...,0
101037,00030805_000.png,No Finding,0,30805,27,M,PA,2048,2500,0.171,0.171,NaN,/content/drive/MyDrive/Capstone Project/nih_ch...,0

In [ ]:
import os

dataset_dir = "/content/drive/MyDrive/Capstone Project/chest_dataset"
os.makedirs(dataset_dir, exist_ok=True)

os.makedirs(dataset_dir + "/No_Finding", exist_ok=True)
os.makedirs(dataset_dir + "/Infiltration", exist_ok=True)

In [ ]:
filteredDf.to_csv("/content/drive/MyDrive/Capstone Project/chest_dataset_labels.csv", index=False)

In [ ]:
import shutil
import os

for _, row in filteredDf.iterrows():

    img_path = row['imagePath']
    label = row['Finding Labels']

    # choose destination folder
    if label == "No Finding":
        dest = os.path.join(dataset_dir, "No_Finding")
    else:
        dest = os.path.join(dataset_dir, "Infiltration")

    # get filename
    filename = os.path.basename(img_path)

    dest_path = os.path.join(dest, filename)

    # check if file already exists
    if not os.path.exists(dest_path):
        shutil.copy(img_path, dest_path)
    else:
        print(f"Skipped (already exists): {filename}")

Streaming output truncated to the last 5000 lines.
Skipped (already exists): 00027752_000.png
Skipped (already exists): 00027753_000.png
Skipped (already exists): 00027754_000.png
Skipped (already exists): 00027755_000.png
Skipped (already exists): 00027756_000.png
Skipped (already exists): 00027757_000.png
Skipped (already exists): 00027757_001.png
Skipped (already exists): 00027759_000.png
Skipped (already exists): 00027762_000.png
Skipped (already exists): 00027763_000.png
Skipped (already exists): 00027763_001.png
Skipped (already exists): 00027764_000.png
Skipped (already exists): 00027765_000.png
Skipped (already exists): 00027765_001.png
Skipped (already exists): 00027765_002.png
Skipped (already exists): 00027766_000.png
Skipped (already exists): 00027767_000.png
Skipped (already exists): 00027768_000.png
Skipped (already exists): 00027769_000.png
Skipped (already exists): 00027770_000.png
Skipped (already exists): 00027771_000.png
Skipped (already exists): 00027773_000.png
Skipped (already exists): 00027774_000.png
Skipped (already exists): 00027775_000.png
Skipped (already exists): 00027775_001.png
Skipped (already exists): 00027776_000.png
Skipped (already exists): 00027777_000.png
Skipped (already exists): 00027778_000.png
Skipped (already exists): 00027780_000.png
Skipped (already exists): 00027781_000.png
Skipped (already exists): 00027782_000.png
Skipped (already exists): 00027782_001.png
Skipped (already exists): 00027782_003.png
Skipped (already exists): 00027782_009.png
Skipped (already exists): 00027783_000.png
Skipped (already exists): 00027784_000.png
Skipped (already exists): 00027784_001.png
Skipped (already exists): 00027784_002.png
Skipped (already exists): 00027784_003.png
Skipped (already exists): 00027784_004.png
Skipped (already exists): 00027784_008.png
Skipped (already exists): 00027784_009.png
Skipped (already exists): 00027784_010.png
Skipped (already exists): 00027786_000.png
Skipped (already exists): 00027787_000.png
Skipped (already exists): 00027787_001.png
Skipped (already exists): 00027788_000.png
Skipped (already exists): 00027789_000.png
Skipped (already exists): 00027789_002.png
Skipped (already exists): 00027789_003.png
Skipped (already exists): 00027789_004.png
Skipped (already exists): 00027790_000.png
Skipped (already exists): 00027791_000.png
Skipped (already exists): 00027792_000.png
Skipped (already exists): 00027794_000.png
Skipped (already exists): 00027794_001.png
Skipped (already exists): 00027795_000.png
Skipped (already exists): 00027796_000.png
Skipped (already exists): 00027799_000.png
Skipped (already exists): 00027799_001.png
Skipped (already exists): 00027799_002.png
Skipped (already exists): 00027801_000.png
Skipped (already exists): 00027802_000.png
Skipped (already exists): 00027802_001.png
Skipped (already exists): 00027802_002.png
Skipped (already exists): 00027804_000.png
Skipped (already exists): 00027804_001.png
Skipped (already exists): 00027805_000.png
Skipped (already exists): 00027807_000.png
Skipped (already exists): 00027808_000.png
Skipped (already exists): 00027808_001.png
Skipped (already exists): 00027809_000.png
Skipped (already exists): 00027809_001.png
Skipped (already exists): 00027809_002.png
Skipped (already exists): 00027809_003.png
Skipped (already exists): 00027809_004.png
Skipped (already exists): 00027809_005.png
Skipped (already exists): 00027809_006.png
Skipped (already exists): 00027809_007.png
Skipped (already exists): 00027809_008.png
Skipped (already exists): 00027809_009.png
Skipped (already exists): 00027809_010.png
Skipped (already exists): 00027809_011.png
Skipped (already exists): 00027810_000.png
Skipped (already exists): 00027811_000.png
Skipped (already exists): 00027812_000.png
Skipped (already exists): 00027813_000.png
Skipped (already exists): 00027814_000.png
Skipped (already exists): 00027818_002.png
Skipped (already exists): 00027820_000.png
Skipped (already exists): 00027821_000.png
Skipped (already exists): 00027821_001.png
Skipped (already exists): 00027821_002.png
Skipped (already exists): 00027821_003.png
Skipped (already exists): 00027821_004.png
Skipped (already exists): 00027822_000.png
Skipped (already exists): 00027823_000.png
Skipped (already exists): 00027824_000.png
Skipped (already exists): 00027824_001.png
Skipped (already exists): 00027825_000.png
Skipped (already exists): 00027826_000.png
Skipped (already exists): 00027827_000.png
Skipped (already exists): 00027828_000.png
Skipped (already exists): 00027828_001.png
Skipped (already exists): 00027828_002.png
Skipped (already exists): 00027829_000.png
Skipped (already exists): 00027830_000.png
Skipped (already exists): 00027831_003.png
Skipped (already exists): 00027832_000.png
Skipped (already exists): 00027833_002.png
Skipped (already exists): 00027833_003.png
Skipped (already exists): 00027833_004.png
Skipped (already exists): 00027833_014.png
Skipped (already exists): 00027833_016.png
Skipped (already exists): 00027834_000.png
Skipped (already exists): 00027835_000.png
Skipped (already exists): 00027836_000.png
Skipped (already exists): 00027837_004.png
Skipped (already exists): 00027838_001.png
Skipped (already exists): 00027838_002.png
Skipped (already exists): 00027838_008.png
Skipped (already exists): 00027838_010.png
Skipped (already exists): 00027838_011.png
Skipped (already exists): 00027838_017.png
Skipped (already exists): 00027838_021.png
Skipped (already exists): 00027838_022.png
Skipped (already exists): 00027838_023.png
Skipped (already exists): 00027840_000.png
Skipped (already exists): 00027841_000.png
Skipped (already exists): 00027842_000.png
Skipped (already exists): 00027842_001.png
Skipped (already exists): 00027842_002.png
Skipped (already exists): 00027842_003.png
Skipped (already exists): 00027843_000.png
Skipped (already exists): 00027844_000.png
Skipped (already exists): 00027845_000.png
Skipped (already exists): 00027846_000.png
Skipped (already exists): 00027847_000.png
Skipped (already exists): 00027847_001.png
Skipped (already exists): 00027847_002.png
Skipped (already exists): 00027848_000.png
Skipped (already exists): 00027850_000.png
Skipped (already exists): 00027850_001.png
Skipped (already exists): 00027851_000.png
Skipped (already exists): 00027851_001.png
Skipped (already exists): 00027852_000.png
Skipped (already exists): 00027854_000.png
Skipped (already exists): 00027854_001.png
Skipped (already exists): 00027855_000.png
Skipped (already exists): 00027856_000.png
Skipped (already exists): 00027857_000.png
Skipped (already exists): 00027857_001.png
Skipped (already exists): 00027857_002.png
Skipped (already exists): 00027858_000.png
Skipped (already exists): 00027859_000.png
Skipped (already exists): 00027859_001.png
Skipped (already exists): 00027860_000.png
Skipped (already exists): 00027860_001.png
Skipped (already exists): 00027861_000.png
Skipped (already exists): 00027861_001.png
Skipped (already exists): 00027862_000.png
Skipped (already exists): 00027862_001.png
Skipped (already exists): 00027863_000.png
Skipped (already exists): 00027863_001.png
Skipped (already exists): 00027864_000.png
Skipped (already exists): 00027864_001.png
Skipped (already exists): 00027864_002.png
Skipped (already exists): 00027864_003.png
Skipped (already exists): 00027864_004.png
Skipped (already exists): 00027865_000.png
Skipped (already exists): 00027866_000.png
Skipped (already exists): 00027866_001.png
Skipped (already exists): 00027866_003.png
Skipped (already exists): 00027866_004.png
Skipped (already exists): 00027867_000.png
Skipped (already exists): 00027867_001.png
Skipped (already exists): 00027867_002.png
Skipped (already exists): 00027867_003.png
Skipped (already exists): 00027867_004.png
Skipped (already exists): 00027868_000.png
Skipped (already exists): 00027869_000.png
Skipped (already exists): 00027870_000.png
Skipped (already exists): 00027870_001.png
Skipped (already exists): 00027872_000.png
Skipped (already exists): 00027873_000.png
Skipped (already exists): 00027873_001.png
Skipped (already exists): 00027874_000.png
Skipped (already exists): 00027875_000.png
Skipped (already exists): 00027876_000.png
Skipped (already exists): 00027877_000.png
Skipped (already exists): 00027878_000.png
Skipped (already exists): 00027879_000.png
Skipped (already exists): 00027879_001.png
Skipped (already exists): 00027879_002.png
Skipped (already exists): 00027880_000.png
Skipped (already exists): 00027881_000.png
Skipped (already exists): 00027881_001.png
Skipped (already exists): 00027882_000.png
Skipped (already exists): 00027884_000.png
Skipped (already exists): 00027886_000.png
Skipped (already exists): 00027886_001.png
Skipped (already exists): 00027887_000.png
Skipped (already exists): 00027888_000.png
Skipped (already exists): 00027888_001.png
Skipped (already exists): 00027889_000.png
Skipped (already exists): 00027889_001.png
Skipped (already exists): 00027890_000.png
Skipped (already exists): 00027892_000.png
Skipped (already exists): 00027892_001.png
Skipped (already exists): 00027893_002.png
Skipped (already exists): 00027894_000.png
Skipped (already exists): 00027894_003.png
Skipped (already exists): 00027896_000.png
Skipped (already exists): 00027898_000.png
Skipped (already exists): 00027899_000.png
Skipped (already exists): 00027901_000.png
Skipped (already exists): 00027902_000.png
Skipped (already exists): 00027903_000.png
Skipped (already exists): 00027904_000.png
Skipped (already exists): 00027905_000.png
Skipped (already exists): 00027905_001.png
Skipped (already exists): 00027905_002.png
Skipped (already exists): 00027906_000.png
Skipped (already exists): 00027907_000.png
Skipped (already exists): 00027908_000.png
Skipped (already exists): 00027908_001.png
Skipped (already exists): 00027908_002.png
Skipped (already exists): 00027908_003.png
Skipped (already exists): 00027909_000.png
Skipped (already exists): 00027910_000.png
Skipped (already exists): 00027912_000.png
Skipped (already exists): 00027912_001.png
Skipped (already exists): 00027912_002.png
Skipped (already exists): 00027912_003.png
Skipped (already exists): 00027912_004.png
Skipped (already exists): 00027912_005.png
Skipped (already exists): 00027912_006.png
Skipped (already exists): 00027912_007.png
Skipped (already exists): 00027912_008.png
Skipped (already exists): 00027913_000.png
Skipped (already exists): 00027914_000.png
Skipped (already exists): 00027915_000.png
Skipped (already exists): 00027916_000.png
Skipped (already exists): 00027917_000.png
Skipped (already exists): 00027918_000.png
Skipped (already exists): 00027919_000.png
Skipped (already exists): 00027920_000.png
Skipped (already exists): 00027922_000.png
Skipped (already exists): 00027924_001.png
Skipped (already exists): 00027925_000.png
Skipped (already exists): 00027925_001.png
Skipped (already exists): 00027926_000.png
Skipped (already exists): 00027927_001.png
Skipped (already exists): 00027927_002.png
Skipped (already exists): 00027927_006.png
Skipped (already exists): 00027927_011.png
Skipped (already exists): 00027927_012.png
Skipped (already exists): 00027927_013.png
Skipped (already exists): 00027927_016.png
Skipped (already exists): 00027927_021.png
Skipped (already exists): 00027927_022.png
Skipped (already exists): 00027927_025.png
Skipped (already exists): 00027927_026.png
Skipped (already exists): 00027927_028.png
Skipped (already exists): 00027927_030.png
Skipped (already exists): 00027927_031.png
Skipped (already exists): 00027927_032.png
Skipped (already exists): 00027927_033.png
Skipped (already exists): 00027927_034.png
Skipped (already exists): 00027927_035.png
Skipped (already exists): 00027927_037.png
Skipped (already exists): 00027927_038.png
Skipped (already exists): 00027927_040.png
Skipped (already exists): 00027927_041.png
Skipped (already exists): 00027928_000.png
Skipped (already exists): 00027929_001.png
Skipped (already exists): 00027929_002.png
Skipped (already exists): 00027929_003.png
Skipped (already exists): 00027929_004.png
Skipped (already exists): 00027929_005.png
Skipped (already exists): 00027929_006.png
Skipped (already exists): 00027929_008.png
Skipped (already exists): 00027930_000.png
Skipped (already exists): 00027930_001.png
Skipped (already exists): 00027931_000.png
Skipped (already exists): 00027932_000.png
Skipped (already exists): 00027933_000.png
Skipped (already exists): 00027934_000.png
Skipped (already exists): 00027935_000.png
Skipped (already exists): 00027935_001.png
Skipped (already exists): 00027935_005.png
Skipped (already exists): 00027935_006.png
Skipped (already exists): 00027935_007.png
Skipped (already exists): 00027935_008.png
Skipped (already exists): 00027935_009.png
Skipped (already exists): 00027935_010.png
Skipped (already exists): 00027935_011.png
Skipped (already exists): 00027935_012.png
Skipped (already exists): 00027936_000.png
Skipped (already exists): 00027937_003.png
Skipped (already exists): 00027938_000.png
Skipped (already exists): 00027938_001.png
Skipped (already exists): 00027938_003.png
Skipped (already exists): 00027938_009.png
Skipped (already exists): 00027939_000.png
Skipped (already exists): 00027940_000.png
Skipped (already exists): 00027941_000.png
Skipped (already exists): 00027941_001.png
Skipped (already exists): 00027943_000.png
Skipped (already exists): 00027943_001.png
Skipped (already exists): 00027943_002.png
Skipped (already exists): 00027944_000.png
Skipped (already exists): 00027944_001.png
Skipped (already exists): 00027945_000.png
Skipped (already exists): 00027946_000.png
Skipped (already exists): 00027947_000.png
Skipped (already exists): 00027948_000.png
Skipped (already exists): 00027949_000.png
Skipped (already exists): 00027950_000.png
Skipped (already exists): 00027951_000.png
Skipped (already exists): 00027952_002.png
Skipped (already exists): 00027952_004.png
Skipped (already exists): 00027954_000.png
Skipped (already exists): 00027955_000.png
Skipped (already exists): 00027956_000.png
Skipped (already exists): 00027957_001.png
Skipped (already exists): 00027957_002.png
Skipped (already exists): 00027957_003.png
Skipped (already exists): 00027958_000.png
Skipped (already exists): 00027960_000.png
Skipped (already exists): 00027961_000.png
Skipped (already exists): 00027961_001.png
Skipped (already exists): 00027961_002.png
Skipped (already exists): 00027962_000.png
Skipped (already exists): 00027962_001.png
Skipped (already exists): 00027964_000.png
Skipped (already exists): 00027965_000.png
Skipped (already exists): 00027966_000.png
Skipped (already exists): 00027967_000.png
Skipped (already exists): 00027968_000.png
Skipped (already exists): 00027969_000.png
Skipped (already exists): 00027969_001.png
Skipped (already exists): 00027969_002.png
Skipped (already exists): 00027969_003.png
Skipped (already exists): 00027970_000.png
Skipped (already exists): 00027971_001.png
Skipped (already exists): 00027972_000.png
Skipped (already exists): 00027975_000.png
Skipped (already exists): 00027975_001.png
Skipped (already exists): 00027975_002.png
Skipped (already exists): 00027977_000.png
Skipped (already exists): 00027978_000.png
Skipped (already exists): 00027978_001.png
Skipped (already exists): 00027979_000.png
Skipped (already exists): 00027979_001.png
Skipped (already exists): 00027980_001.png
Skipped (already exists): 00027981_002.png
Skipped (already exists): 00027982_001.png
Skipped (already exists): 00027982_002.png
Skipped (already exists): 00027982_003.png
Skipped (already exists): 00027982_004.png
Skipped (already exists): 00027982_005.png
Skipped (already exists): 00027983_000.png
Skipped (already exists): 00027984_000.png
Skipped (already exists): 00027985_000.png
Skipped (already exists): 00027985_001.png
Skipped (already exists): 00027985_002.png
Skipped (already exists): 00027985_003.png
Skipped (already exists): 00027986_000.png
Skipped (already exists): 00027987_001.png
Skipped (already exists): 00027987_002.png
Skipped (already exists): 00027988_000.png
Skipped (already exists): 00027989_000.png
Skipped (already exists): 00027990_000.png
Skipped (already exists): 00027991_000.png
Skipped (already exists): 00027992_000.png
Skipped (already exists): 00027993_000.png
Skipped (already exists): 00027996_000.png
Skipped (already exists): 00027996_001.png
Skipped (already exists): 00027996_002.png
Skipped (already exists): 00027997_000.png
Skipped (already exists): 00027997_001.png
Skipped (already exists): 00027997_002.png
Skipped (already exists): 00027997_003.png
Skipped (already exists): 00027999_000.png
Skipped (already exists): 00028000_000.png
Skipped (already exists): 00028000_001.png
Skipped (already exists): 00028000_002.png
Skipped (already exists): 00028003_000.png
Skipped (already exists): 00028006_000.png
Skipped (already exists): 00028006_001.png
Skipped (already exists): 00028008_000.png
Skipped (already exists): 00028009_000.png
Skipped (already exists): 00028010_000.png
Skipped (already exists): 00028011_000.png
Skipped (already exists): 00028013_000.png
Skipped (already exists): 00028013_001.png
Skipped (already exists): 00028013_002.png
Skipped (already exists): 00028014_000.png
Skipped (already exists): 00028015_000.png
Skipped (already exists): 00028015_001.png
Skipped (already exists): 00028017_000.png
Skipped (already exists): 00028020_001.png
Skipped (already exists): 00028020_003.png
Skipped (already exists): 00028020_004.png
Skipped (already exists): 00028020_005.png
Skipped (already exists): 00028020_006.png
Skipped (already exists): 00028020_008.png
Skipped (already exists): 00028021_000.png
Skipped (already exists): 00028022_000.png
Skipped (already exists): 00028023_000.png
Skipped (already exists): 00028024_000.png
Skipped (already exists): 00028025_000.png
Skipped (already exists): 00028025_001.png
Skipped (already exists): 00028026_002.png
Skipped (already exists): 00028027_002.png
Skipped (already exists): 00028027_005.png
Skipped (already exists): 00028028_000.png
Skipped (already exists): 00028029_000.png
Skipped (already exists): 00028030_000.png
Skipped (already exists): 00028031_000.png
Skipped (already exists): 00028031_001.png
Skipped (already exists): 00028032_000.png
Skipped (already exists): 00028032_001.png
Skipped (already exists): 00028033_000.png
Skipped (already exists): 00028034_000.png
Skipped (already exists): 00028034_001.png
Skipped (already exists): 00028034_002.png
Skipped (already exists): 00028034_003.png
Skipped (already exists): 00028035_000.png
Skipped (already exists): 00028036_001.png
Skipped (already exists): 00028037_000.png
Skipped (already exists): 00028038_000.png
Skipped (already exists): 00028039_000.png
Skipped (already exists): 00028039_001.png
Skipped (already exists): 00028040_000.png
Skipped (already exists): 00028041_000.png
Skipped (already exists): 00028041_001.png
Skipped (already exists): 00028041_003.png
Skipped (already exists): 00028042_000.png
Skipped (already exists): 00028043_000.png
Skipped (already exists): 00028043_001.png
Skipped (already exists): 00028044_003.png
Skipped (already exists): 00028044_004.png
Skipped (already exists): 00028044_005.png
Skipped (already exists): 00028044_006.png
Skipped (already exists): 00028045_000.png
Skipped (already exists): 00028045_001.png
Skipped (already exists): 00028047_000.png
Skipped (already exists): 00028048_000.png
Skipped (already exists): 00028049_000.png
Skipped (already exists): 00028050_000.png
Skipped (already exists): 00028050_001.png
Skipped (already exists): 00028050_002.png
Skipped (already exists): 00028051_000.png
Skipped (already exists): 00028052_000.png
Skipped (already exists): 00028053_000.png
Skipped (already exists): 00028054_000.png
Skipped (already exists): 00028055_000.png
Skipped (already exists): 00028056_000.png
Skipped (already exists): 00028057_000.png
Skipped (already exists): 00028058_000.png
Skipped (already exists): 00028059_000.png